// Auto-generated by build pipeline. Do not edit.
#ifndef YAMGG_BOOTSTRAP_JS_H
#define YAMGG_BOOTSTRAP_JS_H

namespace yamgg_bootstrap {

static const char kBootstrapSrc[] = R"YAMJS(
(function () {
    "use strict";

    // ═══════════════════════════════════════════════════════
    // SECTION 1 — HANDLE REGISTRY
    // ═══════════════════════════════════════════════════════
    var table = Object.create(null);
    var nextHandle = 1;
    function alloc(obj) { var id = nextHandle++; table[id] = obj; return id; }
    function get(id) { return Object.prototype.hasOwnProperty.call(table, id) ? table[id] : null; }
    function drop(id) { if (Object.prototype.hasOwnProperty.call(table, id)) delete table[id]; }
    function dropAll() { table = Object.create(null); nextHandle = 1; }

    // ═══════════════════════════════════════════════════════
    // SECTION 2 — REPLY ENVELOPE
    // ═══════════════════════════════════════════════════════
    function reply(id, ok, kind, value, handle, error) {
        var m = { id: id, ok: !!ok };
        if (kind)   m.kind = kind;
        if (value  !== undefined && value  !== null) m.result = value;
        if (handle !== undefined && handle !== null) m.handle = handle;
        if (error)  m.error = String(error);
        try { send({ type: "reply", payload: JSON.stringify(m) }); } catch (e) {}
    }
    function replyHandle(id, h) { reply(id, true,  "handle", null, h); }
    function replyValue(id, v)  { reply(id, true,  "value",  v,    null); }
    function replyVoid(id)      { reply(id, true,  "void",   null, null); }
    function replyError(id, e)  { reply(id, false, "error", null, null, (e && e.message) ? e.message : String(e)); }

    // ═══════════════════════════════════════════════════════
    // SECTION 3 — JNI SIGNATURE PARSER
    // ═══════════════════════════════════════════════════════
    function prim(c) {
        switch (c) {
        case "Z": return "boolean"; case "B": return "byte";
        case "C": return "char";    case "S": return "short";
        case "I": return "int";     case "J": return "long";
        case "F": return "float";   case "D": return "double";
        case "V": return "void";    default:  return c;
        }
    }
    // Use \u005B (escape for "[") to avoid literal bracket in strings.
    var LB = "\u005B";
    var SEMI = ";";
    var SLASH = "/";
    var DOT = ".";
    var ARR_L = "L";
    function parseSig(sig) {
        if (!sig) return [];
        var out = [], i = 0;
        while (i < sig.length) {
            var c = sig.charAt(i);
            if (c === "(") { i++; continue; }
            if (c === ")") break;
            if (c === ARR_L) {
                var e = sig.indexOf(SEMI, i);
                if (e === -1) break;
                out.push(sig.substring(i + 1, e).split(SLASH).join(DOT));
                i = e + 1;
            } else if (c === LB) {
                var d = 0;
                while (sig.charAt(i) === LB) { d++; i++; }
                if (sig.charAt(i) === ARR_L) {
                    var e2 = sig.indexOf(SEMI, i);
                    if (e2 === -1) break;
                    var prefix = "";
                    for (var p = 0; p < d; p++) prefix += LB;
                    out.push(prefix + sig.substring(i + 1, e2).split(SLASH).join(DOT));
                    i = e2 + 1;
                } else {
                    var prefix2 = "";
                    for (var p2 = 0; p2 < d; p2++) prefix2 += LB;
                    out.push(prefix2 + sig.charAt(i));
                    i++;
                }
            } else {
                out.push(prim(c)); i++;
            }
        }
        return out;
    }

    // ═══════════════════════════════════════════════════════
    // SECTION 4 — JSON → JAVA MATERIALIZER
    // ═══════════════════════════════════════════════════════
    function mat(v) {
        if (v === null || v === undefined) return v;
        if (typeof v !== "object") return v;
        if (typeof v.handle === "number") return get(v.handle);
        if ("kind" in v) {
            switch (v.kind) {
            case "int": case "short": case "byte": return v.value | 0;
            case "long":
                return (typeof Int64 === "function") ? Int64(String(v.value)) : Number(v.value);
            case "float": case "double": return Number(v.value);
            case "boolean": return !!v.value;
            case "string":  return String(v.value);
            case "char": {
                var sv = String(v.value);
                return sv.length > 0 ? sv.charAt(0) : String.fromCharCode(0);
            }
            case "null":      return null;
            case "undefined": return undefined;
            case "enum":      return Java.use(v.className).valueOf(v.enumName);
            case "array":     return Java.array(v.elementType, (v.elements || []).map(mat));
            case "construct": {
                var cc = Java.use(v.className);
                var args = (v.args || []).map(mat);
                var inst = cc.$new.apply(cc, args);
                if (v.fields) {
                    for (var fi = 0; fi < v.fields.length; fi++) {
                        inst[v.fields[fi].name] = mat(v.fields[fi].value);
                    }
                }
                return inst;
            }
            default: return v.value;
            }
        }
        if ("value" in v) return v.value;
        return v;
    }

    // ═══════════════════════════════════════════════════════
    // SECTION 5 — LAZY LOADER FORCE
    // ═══════════════════════════════════════════════════════
    var loaderReady = false;
    function ensureLoader() {
        if (loaderReady) return;
        loaderReady = true;
        try {
            Java.performNow(function () {
                try {
                    if (Java.classFactory.loader === null) {
                        var AT  = Java.use("android.app.ActivityThread");
                        var app = AT.currentApplication();
                        if (app !== null) {
                            Java.classFactory.loader = app.getClassLoader();
                            send({ type: "loader_forced", loader: "" + Java.classFactory.loader });
                        } else {
                            send({ type: "loader_pending" });
                        }
                    } else {
                        send({ type: "loader_already" });
                    }
                } catch (e) {
                    send({ type: "loader_error", message: "" + e });
                }
            });
        } catch (e) {
            send({ type: "loader_outer_error", message: "" + e });
        }
    }

    // ═══════════════════════════════════════════════════════
    // SECTION 6 — COMMAND HANDLERS
    // ═══════════════════════════════════════════════════════
    var handlers = {

        cpp_use_class: function (cmd) {
            replyHandle(cmd.id, alloc(Java.use(cmd.className)));
        },

        cpp_get_method: function (cmd) {
            var c = get(cmd.classHandle);
            if (!c) throw new Error("no class handle");
            var m = c[cmd.methodName];
            if (!m) throw new Error("no method: " + cmd.methodName);
            var method = cmd.signature
                ? m.overload.apply(m, parseSig(cmd.signature))
                : ((m.overloads && m.overloads.length > 0) ? m.overloads[0] : m);
            replyHandle(cmd.id, alloc(method));
        },

        cpp_get_field: function (cmd) {
            var cls = Java.use(cmd.className);
            var f = cls[cmd.fieldName];
            if (!f) throw new Error("no field: " + cmd.fieldName);
            var isStatic = false;
            try {
                var fields = cls.class.getDeclaredFields();
                for (var i = 0; i < fields.length; i++) {
                    if (String(fields[i].getName()) === cmd.fieldName) {
                        isStatic = (Number(fields[i].getModifiers()) & 8) !== 0;
                        break;
                    }
                }
            } catch (e) {}
            replyValue(cmd.id, JSON.stringify({ static: isStatic, handle: alloc(f) }));
        },

        cpp_cast: function (cmd) {
            var cls = get(cmd.classHandle);
            var obj = get(cmd.objectHandle);
            if (!cls || !obj) throw new Error("cast: missing handle");
            replyHandle(cmd.id, alloc(Java.cast(obj, cls)));
        },

        cpp_create_string: function (cmd) {
            replyHandle(cmd.id, alloc(Java.use("java.lang.String").$new(cmd.value)));
        },

        cpp_new_instance: function (cmd) {
            var cls = get(cmd.classHandle);
            if (!cls) throw new Error("no class handle");
            var args = (cmd.args || []).map(mat);
            replyHandle(cmd.id, alloc(cls.$new.apply(cls, args)));
        },

        cpp_array_of: function (cmd) {
            var elType = cmd.elementType || "java.lang.Object";
            var elems  = (cmd.elements || []).map(mat);
            replyHandle(cmd.id, alloc(Java.array(elType, elems)));
        },

        cpp_array_length: function (cmd) {
            var arr = get(cmd.handle);
            replyValue(cmd.id, arr ? Number(arr.length) : 0);
        },

        cpp_array_get: function (cmd) {
            var arr = get(cmd.handle);
            var el  = arr ? arr[cmd.index] : null;
            if (el === null || el === undefined) { replyValue(cmd.id, null); return; }
            if (typeof el === "object" && el.$className) replyHandle(cmd.id, alloc(el));
            else replyValue(cmd.id, el);
        },

        cpp_array_set: function (cmd) {
            var arr = get(cmd.handle);
            if (!arr) throw new Error("no array");
            arr[cmd.index] = mat(cmd.value);
            replyVoid(cmd.id);
        },

        cpp_release_handle: function (cmd) {
            drop(cmd.handle);
            replyVoid(cmd.id);
        },

        cpp_list_handles: function (cmd) {
            var list = [];
            for (var k in table) {
                if (!Object.prototype.hasOwnProperty.call(table, k)) continue;
                var o = table[k];
                list.push({ id: Number(k), kind: "java", className: (o && o.$className) || "" });
            }
            replyValue(cmd.id, list);
        },

        cpp_clear_handles: function (cmd) {
            dropAll();
            replyVoid(cmd.id);
        },

        cpp_inspect_handle: function (cmd) {
            var obj = get(cmd.handleId);
            if (!obj) throw new Error("no handle");
            var fields = [];
            try {
                var cls = Java.use(obj.$className);
                var flds = cls.class.getDeclaredFields();
                for (var i = 0; i < flds.length && i < 32; i++) {
                    var f = flds[i];
                    if ((Number(f.getModifiers()) & 8) !== 0) continue;
                    try {
                        f.setAccessible(true);
                        var fv = f.get(obj);
                        fields.push({
                            name: String(f.getName()),
                            type: String(f.getType().getName()),
                            value: (fv === null ? "null" : String(fv))
                        });
                    } catch (e) {}
                }
            } catch (e) {}
            replyValue(cmd.id, {
                className: obj.$className || "unknown",
                stringValue: String(obj),
                fields: fields
            });
        },

        cpp_noop: function (cmd) {
            replyVoid(cmd.id);
        }
    };

    // ═══════════════════════════════════════════════════════
    // SECTION 7 — RECEIVER (yamgg_cmd channel)
    // ═══════════════════════════════════════════════════════
    recv("yamgg_cmd", function (msg) {
        var cmd = null;
        try { cmd = (typeof msg === "string") ? JSON.parse(msg) : msg; } catch (e) { return; }
        if (!cmd || !cmd.action) return;
        try { ensureLoader(); } catch (e) {}
        var h = handlers[cmd.action];
        if (!h) { replyError(cmd.id, new Error("unknown action: " + cmd.action)); return; }
        try { h(cmd); } catch (e) { replyError(cmd.id, e); }
    });

    // ═══════════════════════════════════════════════════════
    // SECTION 8 — READY SIGNALS
    // ═══════════════════════════════════════════════════════
    try { send({ type: "cpp_ready" }); }       catch (e) {}
    try { send({ type: "cpp_ready_final" }); } catch (e) {}
})();
)YAMJS";

} // namespace yamgg_bootstrap

#endif // YAMGG_BOOTSTRAP_JS_H
