#!/usr/bin/env python3
"""
build_bootstrap.py - generate bootstrap_js.h from scripts/bootstrap.js

Reads the standalone JavaScript bootstrap source and emits the C++ header
that embeds it as a raw string literal.

Run this MANUALLY after editing scripts/bootstrap.js:
    python3 scripts/build_bootstrap.py

The generated header is then committed to git and picked up by the CI
build (this script is NOT run in CI).

Usage:
    python3 scripts/build_bootstrap.py [input.js] [output.h]

Defaults:
    input  = scripts/bootstrap.js
    output = app/src/main/jni/all_libs/YAM-G/wrapper/src/bootstrap_js.h

The output header must contain:

    namespace yamgg_bootstrap {
    static const char kBootstrapSrc[] = R"YAMJS(
    ... JS ...
    )YAMJS";
    }

The JS content must not contain the sequence )YAMJS" anywhere,
because that terminates the raw string literal.
"""

import sys
from pathlib import Path

DEFAULT_INPUT  = "scripts/bootstrap.js"
DEFAULT_OUTPUT = "app/src/main/jni/all_libs/YAM-G/wrapper/src/bootstrap_js.h"

TERMINATOR = ')YAMJS"'

PREAMBLE = (
    "// Auto-generated by scripts/build_bootstrap.py - DO NOT EDIT BY HAND.\n"
    "// Source: scripts/bootstrap.js\n"
    "// Regenerate: python3 scripts/build_bootstrap.py\n"
    "#ifndef YAMGG_BOOTSTRAP_JS_H\n"
    "#define YAMGG_BOOTSTRAP_JS_H\n"
    "\n"
    "namespace yamgg_bootstrap {\n"
    "\n"
    'static const char kBootstrapSrc[] = R"YAMJS('
)

EPILOGUE = (
    ')YAMJS";\n'
    "\n"
    "} // namespace yamgg_bootstrap\n"
    "\n"
    "#endif // YAMGG_BOOTSTRAP_JS_H\n"
)


def main():
    if len(sys.argv) > 1:
        input_path = Path(sys.argv[1])
    else:
        input_path = Path(DEFAULT_INPUT)

    if len(sys.argv) > 2:
        output_path = Path(sys.argv[2])
    else:
        output_path = Path(DEFAULT_OUTPUT)

    if not input_path.exists():
        print("ERROR: input not found: " + str(input_path))
        sys.exit(1)

    try:
        js = input_path.read_text(encoding="utf-8")
    except Exception as e:
        print("ERROR: cannot read " + str(input_path) + ": " + str(e))
        sys.exit(1)

    if TERMINATOR in js:
        print("ERROR: JS contains forbidden terminator " + repr(TERMINATOR))
        sys.exit(1)

    if "\x00" in js:
        print("ERROR: JS contains NUL byte")
        sys.exit(1)

    # Informational balance check (does not fail).
    for o, c in (("(", ")"), ("{", "}"), ("[", "]")):
        no = js.count(o)
        nc = js.count(c)
        if no != nc:
            print("WARN: unbalanced " + o + c + ": " + str(no) + " vs " + str(nc))

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as f:
        f.write(PREAMBLE)
        f.write("\n")
        f.write(js)
        if not js.endswith("\n"):
            f.write("\n")
        f.write(EPILOGUE)

    print("Generated " + str(output_path)
          + ": " + str(len(js)) + " bytes, "
          + str(js.count("\n")) + " lines")


if __name__ == "__main__":
    main()
