#!/usr/bin/env python3
"""
build_bootstrap.py — generate bootstrap_js.h from scripts/bootstrap.js

Reads the standalone JavaScript bootstrap source and emits the C++ header
that embeds it as a raw string literal.

Usage:
    python3 scripts/build_bootstrap.py [input.js] [output.h]

Defaults:
    input  = scripts/bootstrap.js
    output = app/src/main/jni/all_libs/YAM-G/wrapper/src/bootstrap_js.h

The output header must contain:

    namespace yamgg_bootstrap {
    static const char kBootstrapSrc[] = R"YAMJS(
    ... JS ...
    )YAMJS";
    }

The JS content must not contain the sequence `)YAMJS"` anywhere,
because that terminates the raw string literal.
"""

import sys
import os
from pathlib import Path

DEFAULT_INPUT  = "scripts/bootstrap.js"
DEFAULT_OUTPUT = "app/src/main/jni/all_libs/YAM-G/wrapper/src/bootstrap_js.h"

TERMINATOR = ')YAMJS"'

HEADER_PREAMBLE = '''// Auto-generated by scripts/build_bootstrap.py — DO NOT EDIT BY HAND.
// Source: scripts/bootstrap.js
// Regenerate: python3 scripts/build_bootstrap.py
#ifndef YAMGG_BOOTSTRAP_JS_H
#define YAMGG_BOOTSTRAP_JS_H

namespace yamgg_bootstrap {

static const char kBootstrapSrc[] = R"YAMJS('''

HEADER_EPILOGUE = ''')YAMJS";

} // namespace yamgg_bootstrap

#endif // YAMGG_BOOTSTRAP_JS_H
'''

def main():
    input_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(DEFAULT_INPUT)
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(DEFAULT_OUTPUT)

    if not input_path.exists():
        print(f"ERROR: input not found: {input_path}")
        sys.exit(1)

    js = input_path.read_text(encoding="utf-8")

    # Sanity: forbid the literal terminator inside the JS
    if TERMINATOR in js:
        print(f"ERROR: JS contains forbidden terminator '{TERMINATOR}'")
        sys.exit(1)

    # Sanity: forbid NUL bytes
    if "\x00" in js:
        print("ERROR: JS contains NUL byte")
        sys.exit(1)

    # Sanity: balance braces (informational only)
    for o, c in [("{","}"),("(",")"),("[","]")]:
        no, nc = js.count(o), js.count(c)
        if no != nc:
            print(f"WARN: unbalanced {o}{c}: {no} vs {nc}")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as f:
        f.write(HEADER_PREAMBLE)
        f.write("\n")
        f.write(js)
        if not js.endswith("\n"):
            f.write("\n")
        f.write(HEADER_EPILOGUE)

    print(f"Generated {output_path}: {len(js)} bytes, {js.count(chr(10))} lines")

if __name__ == "__main__":
    main()
